import React, { useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { selectSettings, setModelName } from '@/store/features/settings/settingsSlice';
import { selectModels } from '@/store/features/models/modelsSlice';
import { sendRequested, markResponseStale } from '@/store/features/scratchpad/scratchpadSlice';
import { DisplayModelInfo } from '@/types/storage';

// req:scratchpad-composer: Composer UI for the scratchpad mode — allows the user to type a
// prompt, choose a model, and send the request. Cmd/Ctrl+Enter also triggers send.
const ScratchpadComposer: React.FC = () => {
  const dispatch = useDispatch();
  const { modelName } = useSelector(selectSettings);
  const { models } = useSelector(selectModels);
  const [draft, setDraft] = useState('');

  const onSend = (): void => {
    if (!draft.trim()) return;
    dispatch(sendRequested({ raw_content: draft, modelName }));
    setDraft('');
  };

  return (
    <div data-testid="scratchpad-composer">
      <select
        data-testid="scratchpad-model-select"
        value={modelName}
        onChange={(e) => {
          // Changing model marks the existing response stale so the user
          // knows the displayed response was generated by a different model.
          dispatch(setModelName(e.target.value));
          dispatch(markResponseStale());
        }}
      >
        {models.map((m: DisplayModelInfo) => (
          <option key={m.id} value={m.id}>{m.name}</option>
        ))}
      </select>
      <textarea
        data-testid="scratchpad-input"
        value={draft}
        onChange={(e) => setDraft(e.target.value)}
        onKeyDown={(e) => {
          if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) onSend();
        }}
      />
      <button data-testid="scratchpad-send" onClick={onSend}>Send</button>
    </div>
  );
};

export default ScratchpadComposer;
