name: Bundle Size

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.13.0
        with:
          enable-cache: 'true'

      - name: Build
        run: devbox run -- npm install && devbox run -- npm run build

      - name: Compressed Size
        uses: preactjs/compressed-size-action@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          build-script: 'build-dummy'
          pattern: "dist/**/*.{js,css,html,svg}"
