name: Deploy
on:
  push:
    branches: ['main']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

env:
  GITHUB_ACTIONS: true
  FORCE_COLOR: 1

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
    - name: Checkout project
      uses: actions/checkout@v4

    - name: Install devbox
      uses: jetify-com/devbox-install-action@v0.13.0
      with:
        enable-cache: 'true'

    - name: Cache node modules
      uses: actions/cache@v4
      id: npm-cache
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Dependencies
      run: devbox run -- npm ci

    - name: Typecheck
      run: devbox run -- npm run typecheck

    - name: Lint
      run: devbox run -- npm run lint

    - name: Test
      run: devbox run -- npm run test:e2e

    - name: Build
      run: devbox run -- npm run build

    # Workaround for SPAs on GitHub Pages. By copying index.html to 404.html, we ensure that
    # any direct navigation or page refresh on a client-side route (e.g., /session/123)
    # will serve the main app, allowing the client-side router to take over.
    - name: Prepare for GitHub Pages SPA
      run: cp dist/index.html dist/404.html

    - name: List build artifacts
      run: ls -lh dist

    - name: Deploy to GitHub Pages 🚀
      uses: JamesIves/github-pages-deploy-action@920cbb300dcd3f0568dbc42700c61e2fd9e6139c # v4 specific commit
      with:
        folder: dist # Path relative to workspace root
        # branch: gh-pages # Default is gh-pages, uncomment to specify a different one
        clean: true
        single-commit: true
