name: Deploy
on:
  push:
    branches: ['main']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

env:
  GITHUB_ACTIONS: true
  FORCE_COLOR: 1

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
    - name: Checkout project
      uses: actions/checkout@v4

    - name: Install devbox
      uses: jetify-com/devbox-install-action@v0.13.0
      with:
        enable-cache: 'true'

    - name: Cache Cargo registry and git dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ runner.os }}-cargo-deps-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-deps-

    - name: Cache Cargo target directory
      uses: actions/cache@v4
      with:
        path: target # Path relative to workspace root
        key: ${{ runner.os }}-cargo-target-${{ github.sha }}-${{ hashFiles('Cargo.lock') }}-${{ hashFiles('src/**/*.rs', 'examples/**/*.rs', 'tests/**/*.rs') }}
        restore-keys: |
          ${{ runner.os }}-cargo-target-${{ github.sha }}-${{ hashFiles('Cargo.lock') }}-
          ${{ runner.os }}-cargo-target-

    - name: Run CI Checks (Format, Lint, Test, Debug Build)
      run: devbox run -- just ci-checks

    - name: Build Release Artifact
      run: devbox run -- just build-release

    - name: Deploy to GitHub Pages 🚀
      uses: JamesIves/github-pages-deploy-action@920cbb300dcd3f0568dbc42700c61e2fd9e6139c # v4 specific commit
      with:
        folder: dist # Path relative to workspace root
        # branch: gh-pages # Default is gh-pages, uncomment to specify a different one
        clean: true
        single-commit: true
