name: Vercel Preview Deployment
permissions:
  contents: read
  pull-requests: write  # Required for PR commenting

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request:
    branches-ignore:
      - main
  # Optional: still run on push to branch without PR
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.13.0
        with:
          enable-cache: 'true'

      - name: Cache Cargo registry and git dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-deps-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-deps-

      - name: Cache Cargo target directory
        uses: actions/cache@v4
        with:
          path: target # Path relative to workspace root
          key: ${{ runner.os }}-cargo-target-${{ github.sha }}-${{ hashFiles('Cargo.lock') }}-${{ hashFiles('src/**/*.rs', 'examples/**/*.rs', 'tests/**/*.rs') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-${{ github.sha }}-${{ hashFiles('Cargo.lock') }}-
            ${{ runner.os }}-cargo-target-

      - name: Run CI Checks (Format, Lint, Test, Debug Build)
        run: devbox run -- just ci-checks

      - name: Build Release Artifact
        run: devbox run -- just build-release

      - name: Preview Deploy
        id: preview
        uses: amondnet/vercel-action@v25.1.1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-comment: false
          working-directory: ./dist
