name: Test
on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  GITHUB_ACTIONS: true
  FORCE_COLOR: 1
  # RUST_BACKTRACE: 1 # Uncomment for verbose Rust backtraces on test failures

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
    - name: Checkout project
      uses: actions/checkout@v4

    - name: Install devbox
      uses: jetify-com/devbox-install-action@v0.13.0
      with:
        enable-cache: 'true'

    - name: Cache node modules
      uses: actions/cache@v4
      id: npm-cache
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Dependencies
      run: devbox run -- npm ci

    - name: Typecheck
      run: devbox run -- npm run typecheck

    - name: Test unit
      run: devbox run -- npm run test:unit

    - name: Test e2e
      run: devbox run -- npm run test:e2e

    - name: Lint
      run: devbox run -- npm run lint

