name: Test
on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  GITHUB_ACTIONS: true
  FORCE_COLOR: 1
  # RUST_BACKTRACE: 1 # Uncomment for verbose Rust backtraces on test failures

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
    - name: Checkout project
      uses: actions/checkout@v4

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Magic Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Cache pnpm store
      uses: actions/cache@v4
      with:
        path: ~/.local/share/pnpm/store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - name: Install Dependencies
      run: nix develop --command pnpm install --frozen-lockfile

    - name: Typecheck
      run: nix develop --command pnpm typecheck

    - name: Test unit
      run: nix develop --command pnpm test:unit

    - name: Test e2e
      run: nix develop --command pnpm test:e2e

    - name: Lint
      run: nix develop --command pnpm lint
